A **matrix product** is the operation when we have 2 matrices and we perform the dot product of all combinations of rows from the first matrix and the columns of the seconds matrix, which results in a matrox of those **dot products**.

First, we do the matrix product on vectors. We can have two types of vectors, a column vector and a row vector. All though they are vectors they can be represented as matrices with one of their dimensions having size 1.

a = [1 2 3]  
  
a is a row vector. It looks similar to a vectora (with an arrow above it). The difference between row vector and a vector are commas between values and the arrow above the symbol a is missing on a row vetor. **The name row vector imples it is a vector of a row in a matrix**.  
  
.....[2]  
b=|3|  
.....[4]  
  

b, is instead called a column vector because it is a column of a matrix.  

In [1]:
import numpy as np

In [2]:
a = [1, 2, 3] # list
print(np.array([a]))

[[1 2 3]]


We encased the list a in brackets [a] before converting it to an array. We can also do as below. As row vectors and column vectors are technically matrices, we do not denote them with vector arrows anymore. We can now perform a matrix product on them and the result becomes a matrix also, but in this case it will contain just one single value.

In [3]:
print(np.expand_dims(np.array(a), axis=0))

[[1 2 3]]


**Transpose**

We perform a martix product on these two matrices instead of dot product which gives us a result as a one value matrix. The shape of the matrixes are (1,**3**) and (**3**,1). The **index 1** of first matrix and **index 0** of the second matrix must match. They will not match unless we transpose. That is the reason we need to **transpose** the second matrix. 

In [4]:
a = [1, 2, 3]
b = [2, 3, 4]

a = np.array([a])
b = np.array([b]).T  # transpose

print(np.dot(a,b)) 
# the dot product and matrix products are both implemented in a single
# method in numpy: np.dot()

[[20]]


**Layer of Neurons**
  
We add a layer of neurons and a batch of data. Let´s consider the inputs and weights again. We need to perform the dot products on all of the vectors that consists of both input and weight matrices, that is the matri product from above. We only need to do the transposition on the dot products second argument, which is the matrix of weights, to turn the row vectors it currently has into column vectors.

In the first examples we could use the dot product without the transpose because inputs were just one vector. When inputs are a tach of input data, a matrix, we need to perform the matrix product. Thus the shape of the index 1 of the first matrix and index 0 of the second matrix must match.

In [7]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

In [15]:
inputs = np.array([inputs])
weights = np.array([weights])
print(inputs)
print(weights)

[[[[ 1.   2.   3.   2.5]
   [ 2.   5.  -1.   2. ]
   [-1.5  2.7  3.3 -0.8]]]]
[[[ 0.2   0.8  -0.5   1.  ]
  [ 0.5  -0.91  0.26 -0.5 ]
  [-0.26 -0.27  0.17  0.87]]]


Now the shapess are (3,**4**) and (**3**,4). There is no  match. So we need to transpose to perform the matrix product.

In [16]:
print(np.array([inputs]))
print(np.array([weights]).T)

[[[[[ 1.   2.   3.   2.5]
    [ 2.   5.  -1.   2. ]
    [-1.5  2.7  3.3 -0.8]]]]]
[[[[ 0.2 ]]

  [[ 0.5 ]]

  [[-0.26]]]


 [[[ 0.8 ]]

  [[-0.91]]

  [[-0.27]]]


 [[[-0.5 ]]

  [[ 0.26]]

  [[ 0.17]]]


 [[[ 1.  ]]

  [[-0.5 ]]

  [[ 0.87]]]]


Now the shapes of the matrices match (3,**4**) and (**4**,3)  
  
The dot products takes the row from the first array and the column of the second array, both were previously aligned by row, after transposing the second array the shape is changes to be aligned by column. The output of the matrix product wwill consist of outputs of all neurons after hte operation is performed on each input sample:

In [21]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

np.dot(inputs, np.array(weights).T)

array([[ 2.8  , -1.79 ,  1.885],
       [ 6.9  , -4.81 , -0.3  ],
       [-0.59 , -1.949, -0.474]])

In [23]:
biases = [2.0, 3.0, 0.5] # adding the biases
layer_outputs = np.dot(inputs, np.array(weights).T) + biases

print(layer_outputs) # this is the matrix product plus the biases

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


The result shows that the neural network takes in a group of input samples and outpus a group of predictions. If one has used any DL libraries, this is why you pass in a list of inputs, even if it is just one feature set) and are returned a list or predictions, even if there is only one prediction.