In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

nnfs.init()

In [18]:
# Dense layer
class Layer_Dense:
    
    # Layer initialization
    def __init__(self, n_inputs, n_neurons):
        # Initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        
        # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases

# ReLU activation
class Activation_ReLU:
    
    # Forward pass
    def forward(self, inputs):
        # Calculate output values from inputs
        self.output = np.maximum(0, inputs)

# Softmax activation
class Activation_Softmax:
        
    # Forward pass
    def forward(self, inputs):

        # Get unnormalized probabilities
        exp_values = np.exp(inputs - np.max(inputs, axis=1,
                                            keepdims=True))

        # Normalize them for each sample
        probabilities = exp_values / np.sum(exp_values, axis=1,
                                            keepdims=True)
        
        self.output = probabilities
        
# Create dataset
X, y = spiral_data(samples=100, classes=3)

# Create Dense layer with 2 input features and 3 outpus values
dense1 = Layer_Dense(2,3)

# Create RU activation (to be used with Dense Layer)
activation1 = Activation_ReLU()

# Create second Dense layer with 3 input features (as we take output
# of previous layer here) and 3 output values
dense2 = Layer_Dense(3,3)

# Create Softmax activation (to be used with Dense Layer)
activation2 = Activation_Softmax()

# Make a forward pass of the training data through this layer
dense1.forward(X)

# Make a forward pass through activation function
# it takes the output of first dense layer here
activation1.forward(dense1.output)

# Make a forward pass thgouth second Dense layer
# it takes outputs of activation function of first layer as inputs
dense2.forward(activation1.output)

# Make a forward pass through activation function
# it takes the output of second dense layer here
activation2.forward(dense2.output)

# Let´s see the output of the first few samples:
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33333316 0.3333335  0.33333328]
 [0.33333334 0.33333334 0.33333334]
 [0.33333245 0.33333436 0.33333316]
 [0.33333296 0.33333376 0.33333325]]


We have now completed what we need for forward-passing data thgouth our model. We used ReLU activation function on the hidden layer, which works on a per-neuron basis. We additonally used Softmax activation function for the output layer since it accepts non-normalized values as input and outputs a probability distribution, which we are using as confidence scores for each class. Remember, even though neurons are interconnected, they each have their respective weights and biases and are not "normalized" with each other.

As we can see, our exampe model is currently random. To remedy this we  need a way to calculate how wrong the neural network is at current predictions and begin adjusting weights and biases to decreas error over time. This we do in the next step by quantifying how wrong th emodel is through what is defined as a loss **function**.